
___

<a href='https://www.darshan.ac.in/'> <img src='https://gtu.darshan.ac.in/Upload/Logo/DIET_Logo.svg' /></a>
___
<pre>
<center><b>Python for Data Science - 3150713</b></center>
<center><b>Lab - 5</b></center>    
<pre>

# 1)	Scrape the data of Faculty and news data from darshan university website.

In [143]:
import requests
import bs4
i=1

alldept = [
    "https://www.darshan.ac.in/engineering/computer/faculty",
    "https://www.darshan.ac.in/engineering/civil/faculty",
    "https://www.darshan.ac.in/engineering/electrical/faculty",
    "https://www.darshan.ac.in/engineering/mechanical/faculty"
]

for dept in alldept :
    data = requests.get(dept)
    # print(data.text)
    soap = bs4.BeautifulSoup(data.text,'lxml')
    allfaculty = soap.select("body > main > div:nth-child(5) > div > div > div.col-lg-8.col-xl-9.g-font-size-14 > div > div > div ")
    # print(allfaculty)
    for fac in allfaculty:
        name = fac.select('h2')[0].text.strip()
        desig = fac.select('span')[0].text.strip()
        degree = fac.select('span')[1].text.strip()
        exp = fac.select('span')[3].text.strip()
        working = fac.select('span')[5].text.strip()
        print(i," ->",name,"\n      Designation : ",desig,"\n      Degree : ",degree,"\n      Experience : ",exp,"\n      Working since : ",working)
        i+=1

1  -> Dr. Gopi Sanghani
      Designation :  Dean - School of Computer Science
      Degree :  Ph.D. , M.E. (CE)
      Experience :  22+ Years
      Working since :  Jul-2012
2  -> Dr. Nilesh Gambhava
      Designation :  Professor
      Degree :  Ph.D. , M.E. (CE)
      Experience :  19+ Years
      Working since :  Jul-2009
3  -> Dr. Pradyumansinh Jadeja
      Designation :  Associate Professor
      Degree :  Ph.D., M.E. (CE)
      Experience :  17+ Years
      Working since :  Jul-2009
4  -> Prof. Maulik Trivedi
      Designation :  Assistant Professor
      Degree :  BE(CE), M.Tech.(CSE), Ph.D.(Pursuing)
      Experience :  14+ Years
      Working since :  Jun-2009
5  -> Prof. Dixita Kagathara
      Designation :  Assistant Professor
      Degree :  M.Tech. (Web Technology)
      Experience :  13+ Years
      Working since :  Jul-2009
6  -> Prof. Rupesh Vaishnav
      Designation :  Assistant Professor
      Degree :  M.E. (CE)
      Experience :  14+ Years
      Working since :  May-2013
7  -> Prof. Swati Sharma
      Designation :  Assistant Professor
      Degree :  M.Tech. (CSE)
      Experience :  14+ Years
      Working since :  May-2013
8  -> Prof. Arjun Bala
      Designation :  Assistant Professor
      Degree :  M.Tech. (CSE)
      Experience :  12+ Years
      Working since :  Jul-2013
9  -> Prof. Mayur Padia
      Designation :  Assistant Professor
      Degree :  M.E. (CE)
      Experience :  14+ Years
      Working since :  Jul-2011
10  -> Prof. Vijay Shekhat
      Designation :  Assistant Professor
      Degree :  M.E. (CE)
      Experience :  10+ Years
      Working since :  Jun-2012
11  -> Prof. Naimish Vadodariya
      Designation :  Assistant Professor
      Degree :  M.E. (CE)
      Experience :  9+ Years
      Working since :  Jun-2015
12  -> Prof. UmeshKumar Thoriya
      Designation :  Assistant Professor
      Degree :  M.Tech. (CSE)
      Experience :  9+ Years
      Working since :  Jul-2015
13  -> Prof. Jayesh Vagadiya
      Designation :  Assistant Professor
      Degree :  M.E (CE)
      Experience :  7+ Years
      Working since :  Jul-2015
14  -> Prof. Krunal Vyas
      Designation :  Assistant Professor
      Degree :  M.Tech.(ICT), B.E. (EC)
      Experience :  8+ Years
      Working since :  Jun-2018
15  -> Prof. Jay Dhamsaniya
      Designation :  Assistant Professor
      Degree :  PG Diploma (Software Development), B.Tech. (E.C.)
      Experience :  10+ Years
      Working since :  Jul-2012
16  -> Prof. Mehul Bhundiya
      Designation :  Assistant Professor
      Degree :  BE (CE), ME (CE)
      Experience :  8+ Years
      Working since :  Aug-2018
17  -> Prof. Vaseem Ghada
      Designation :  Assistant Professor
      Degree :  M.Tech (ICT), B.E (IT)
      Experience :  13+ Years
      Working since :  Aug-2021
18  -> Prof. Hemang Chath
      Designation :  Assistant Professor
      Degree :  BE(CE), ME(CE - Pursuing)
      Experience :  12+ Years
      Working since :  Sep-2021
19  -> Prof. Charvin Kothia
      Designation :  Assistant Professor
      Degree :  B.E. (CE)
      Experience :  2+ Years
      Working since :  Nov-2020
20  -> Prof. Madhuresh Fichadiya
      Designation :  Assistant Professor
      Degree :  B.E.(CE)
      Experience :  1+ Years
      Working since :  Jul-2021
21  -> Prof. Vishal Kansagara
      Designation :  Assistant Professor
      Degree :  M. TECH. (ICT)
      Experience :  8+ Years
      Working since :  Nov-2021
22  -> Prof. Dharmik Vasiyani
      Designation :  Assistant Professor
      Degree :  ME(CE)
      Experience :  5+ Years
      Working since :  Nov-2021
23  -> Prof. Shruti Maniar
      Designation :  Assistant Professor
      Degree :  ME(CE),BE(IT)
      Experience :  6+ Years
      Working since :  Dec-2021
24  -> Prof. Bhushan Joshi
      Designation :  Assistant Professor
      Degree :  BE(EC), ME(EC Embedded Systems)
      Experience :  5+ Years
      Working since :  Jun-2022
25  -> Prof. Kishankumar Jogi
      Designation :  Assistant Professor
      Degree :  B.E.Electrical
      Experience :  7+ Years
      Working since :  Aug-2022
26  -> Prof. Dipak Jivani
      Designation :  Head of The Department
      Degree :  Ph.D (Pursuing), M.Tech. (CASAD), B.E. (Civil)
      Experience :  14+ Years
      Working since :  Jan-2013
27  -> Prof. Mansukh Barasara
      Designation :  Professor
      Degree :  M.E. (Civil), B.E. (Civil)
      Experience :  35+ Years
      Working since :  Jun-2009
28  -> Dr. Ujjval Solanki
      Designation :  Associate Professor
      Degree :  Ph.D., M.Tech. (Transportation Engineering), B.E. (Civil, AM...
      Experience :  32+ Years
      Working since :  Jun-2009
29  -> Prof. Kaushik Koradia
      Designation :  Associate Professor
      Degree :  Ph.D (Pursuing), M.E. (Structure), B.E. (Civil)
      Experience :  20+ Years
      Working since :  Jul-2010
30  -> Prof. Chetan Solanki
      Designation :  Assistant Professor
      Degree :  M.E. (Structural), B.E. (Civil), Diploma (Civil)
      Experience :  10+ Years
      Working since :  Jun-2012
31  -> Prof. Vitrag Dholakia
      Designation :  Assistant Professor
      Degree :  M.Sc. (Microbiology), B.Sc. (Microbiology), B.Ed
      Experience :  14+ Years
      Working since :  Jul-2010
32  -> Prof. Jilkumar Malli
      Designation :  Assistant Professor
      Degree :  M.E.(Structural), B.E.(Civil)
      Experience :  9+ Years
      Working since :  Jun-2013
33  -> Prof. Akshar Fataniya
      Designation :  Assistant Professor
      Degree :  M.Tech. (Construction Technology), B.E. (Civil), Diploma (Ci...
      Experience :  7+ Years
      Working since :  Jun-2015
34  -> Prof. Kamlesh Vala
      Designation :  Assistant Professor
      Degree :  Ph.D. (Pursuing), M.Tech. (Geo-Tech), B.E. (Civil)
      Experience :  6+ Years
      Working since :  Jun-2016
35  -> Prof. Niraj Patel
      Designation :  Assistant Professor
      Degree :  M.Tech. (Construction Technology), B.E. (Civil)
      Experience :  7+ Years
      Working since :  Jun-2015
36  -> Prof. Chintan Raichura
      Designation :  Assistant Professor
      Degree :  Ph.D (Pursuing), M.Tech. (Construction Technology), B.E. (Ci...
      Experience :  6+ Years
      Working since :  Jun-2017
37  -> Prof. Milan Gohel
      Designation :  Assistant Professor
      Degree :  M.E. (Chemical), B.E. (Chemical), Diploma (Chemical)
      Experience :  8+ Years
      Working since :  May-2014
38  -> Prof. Pratik Viramgama
      Designation :  Assistant Professor
      Degree :  M.E. (Structural), B.E. (Civil)
      Experience :  5+ Years
      Working since :  Jun-2021
39  -> Prof. Ketan Abhani
      Designation :  Assistant Professor
      Degree :  Ph.D (Pursuing), M.E. (Structure), B.E. (Civil)
      Experience :  4+ Years
      Working since :  Mar-2021
40  -> Prof. Dhaval Jalalpara
      Designation :  Assistant Professor
      Degree :  M.E. (Transportation), B.E. (Civil)
      Experience :  1+ Years
      Working since :  Feb-2021
41  -> Prof. Sagar Galani
      Designation :  Assistant Professor
      Degree :  B.E. (Civil)
      Experience :  6+ Years
      Working since :  Jun-2016
42  -> Prof. Mahipalsinh Chauhan
      Designation :  Assistant Professor
      Degree :  B.E. (Environment Engineering)
      Experience :  4+ Years
      Working since :  Jul-2018
43  -> Prof. Nikunj Geriya
      Designation :  Assistant Professor
      Degree :  B.E. (Civil)
      Experience :  4+ Years
      Working since :  Jun-2018
44  -> Mr. Pravin Metaliya
      Designation :  Lab Assistant
      Degree :  M.E. (Transportation), B.E. (Civil)
      Experience :  2+ Years
      Working since :  Jan-2020
45  -> Mr. Kantilal Vadsola
      Designation :  Lab Assistant
      Degree :  Diploma (Civil)
      Experience :  31+ Years
      Working since :  Jun-2009
46  -> Mr. Rakesh Kanzariya
      Designation :  Lab Assistant
      Degree :  B. E. (Civil)
      Experience :  5+ Years
      Working since :  Mar-2018
47  -> Prof. Deepkumar Hadvani
      Designation :  Assistant Professor
      Degree :  M.E. (Structure), B.E. (Civil)
      Experience :  0+ Years
      Working since :  Jul-2022
48  -> Prof. Arjun Chavada
      Designation :  Assistant Professor
      Degree :  BE(Civil)
      Experience :  1+ Years
      Working since :  Jul-2022
49  -> Mr. Deepraj Patadia
      Designation :  Assistant Professor
      Degree :  BE (Civil), ME (Civil)
      Experience :  2+ Years
      Working since :  Sep-2022

50  -> Prof. Anil Kansagara
      Designation :  Assistant Professor
      Degree :  M.E. (Electrical Power System)
      Experience :  14+ Years
      Working since :  Jul-2009
51  -> Prof. Bhavin Kanani
      Designation :  Assistant Professor
      Degree :  M.Tech. (Power Apparatus & Systems)
      Experience :  14+ Years
      Working since :  Jul-2011
52  -> Prof. Bhavesh Dave
      Designation :  Assistant Professor
      Degree :  M.E. (Power Electronics & Electrical Drives)
      Experience :  12+ Years
      Working since :  Oct-2010
53  -> Prof. Hardik Lakhani
      Designation :  Assistant Professor
      Degree :  M.Tech (Power Electronics & Drives)
      Experience :  10+ Years
      Working since :  Jan-2013
54  -> Prof. Raj Mehta
      Designation :  Assistant Professor
      Degree :  M.Tech (PED)
      Experience :  4+ Years
      Working since :  Mar-2021
55  -> Dr. Jignasa Mehta
      Designation :  Dean - School of Engineering, Head
      Degree :  Ph.D. (Mechanical), M.E. (Machine Design), B.E. (Mechanical ...
      Experience :  27+ Years
      Working since :  Jun-2021
56  -> Dr. Ashvin Makadia
      Designation :  Professor
      Degree :  Ph.D. (Mechanical Engineering) , M.Tech. (CAD/CAM), B.E. (Me...
      Experience :  28+ Years
      Working since :  May-2009
57  -> Prof. Bhavin Vegada
      Designation :  Assistant Professor
      Degree :  M.Tech. (Thermal Engineering), B.E. (Mechanical Engineering)...
      Experience :  11+ Years
      Working since :  Jun-2011
58  -> Prof. Vimal Limbasiya
      Designation :  Assistant Professor
      Degree :  M.Tech. (CAD/CAM), B.E. (Mechanical Engineering)
      Experience :  11+ Years
      Working since :  Jul-2011
59  -> Prof. Ankur Tank
      Designation :  Assistant Professor
      Degree :  B.E. (Mechanical Engineering)
      Experience :  11+ Years
      Working since :  Aug-2011
60  -> Prof. Paras Vegada
      Designation :  Assistant Professor
      Degree :  B.E. (Mechanical Engineering)
      Experience :  11+ Years
      Working since :  Jul-2013
61  -> Prof. Sagar Kanjiya
      Designation :  Assistant Professor
      Degree :  M.E. (Thermal Engineering), B.E. (Mechanical Engineering)
      Experience :  8+ Years
      Working since :  Jun-2014
62  -> Prof. Yash Tank
      Designation :  Assistant Professor
      Degree :  M.Tech. (Manufacturing Engineering), B.E. (Mechanical Engine...
      Experience :  2+ Years
      Working since :  Aug-2021
63  -> Mr. Prakashchandra Parajiya
      Designation :  Lab Assistant
      Degree :  D.E. (Mechanical Engineering)
      Experience :  14+ Years
      Working since :  May-2012
64  -> Prof. Ashish  Malkan
      Designation :  Assistant Professor
      Degree :  B.E. (ME), M.E. (ME)
      Experience :  0+ Years
      Working since :  Aug-2022

# 2) Scrape the data of student placement from darshan university website.

In [281]:
import requests
import bs4
i=1
data = requests.get("https://darshan.ac.in/placement/list/engineering/computer/2023")
# print(data.text)

soap = bs4.BeautifulSoup(data.text,'lxml')
allstu = soap.select("body > main > div:nth-child(5) > div > div > div.col-lg-8.col-xl-9.g-font-size-14.g-mb-30 > div.g-pt-20 > div.row.g-px-4.g-px-5--sm.g-px-5--md >div")
# print(allfaculty)
for s in allstu:
    name = s.select("h2")[0].text.strip()
    city = s.select("p")[4].text.strip()
    ctc = s.select('span')[1].text.strip()
    enroll = s.select('p')[0].text.strip()
    print(i," ->",name,"\n      Enrollment : ",enroll,"\n      CTC per Annum : ",ctc,"\n      City : ",city,"\n")
    i+=1

1  -> KATHANLUNAGARIYA
      Enrollment :  190540107121
      CTC per Annum :  20.00 Lac
      City :  Gurgaon

2  -> DHAVALBERA
      Enrollment :  190540107007
      CTC per Annum :  10.00 Lac
      City :  Ahmedabad

3  -> SOHAMJOSHI
      Enrollment :  190540107085
      CTC per Annum :  8.00-9.00 Lac
      City :  Ahmedabad

4  -> IKSHIKACHOTAI
      Enrollment :  190540107030
      CTC per Annum :  8.00-9.00 Lac
      City :  Ahmedabad

5  -> DRASHTIATKOTIYA
      Enrollment :  190540107005
      CTC per Annum :  8.00-9.00 Lac
      City :  Ahmedabad

6  -> MIRAL SANGANI
      Enrollment :  190540107181
      CTC per Annum :  6.00-7.00 Lac
      City :  Ahmedabad

7  -> SWAPNILKATHIRIYA
      Enrollment :  190540107106
      CTC per Annum :  6.00-7.00 Lac
      City :  Ahmedabad

8  -> SURAJKUSHVAHA
      Enrollment :  190540107116
      CTC per Annum :  6.00-7.00 Lac
      City :  Ahmedabad

9  -> RAJANPANDYA
      Enrollment :  190540107148
      CTC per Annum :  6.00-7.00 Lac
      City :  Ahmedabad

10  -> DRASHTIKANSAGARA
      Enrollment :  200540107516
      CTC per Annum :  6.00-7.00 Lac
      City :  Ahmedabad

11  -> SMITPIPARAVA
      Enrollment :  190540107171
      CTC per Annum :  6.00-7.00 Lac
      City :  Ahmedabad

12  -> VATSALPATEL
      Enrollment :  200540107523
      CTC per Annum :  6.00 Lac
      City :  Rajkot

13  -> MIHIRKHUNT
      Enrollment :  190540107109
      CTC per Annum :  4.80 Lac
      City :  Ahmedabad

14  -> SUNNY MARTHAK
      Enrollment :  200540107519
      CTC per Annum :  4.80 Lac
      City :  Ahmedabad

15  -> JAYGOHEL
      Enrollment :  200540107520
      CTC per Annum :  4.80 Lac
      City :  Ahmedabad

16  -> ABHAYCHOTHANI
      Enrollment :  190540107032
      CTC per Annum :  4.80 Lac
      City :  Ahmedabad

17  -> KHYATIUPADHYAY
      Enrollment :  190540107209
      CTC per Annum :  4.80 Lac
      City :  Ahmedabad

18  -> NIYANTAAAMBALIYA
      Enrollment :  190540107001
      CTC per Annum :  4.80 Lac
      City :  Ahmedabad

19  -> SHREYGANDHI
      Enrollment :  190540107064
      CTC per Annum :  4.80 Lac
      City :  Ahmedabad

20  -> VASUDEDAKIYA
      Enrollment :  190540107043
      CTC per Annum :  4.32 - 4.80 Lac
      City :  Ahmedabad

21  -> KRUTIBHIMANI
      Enrollment :  190540107014
      CTC per Annum :  4.32 - 4.80 Lac
      City :  Ahmedabad

22  -> SHREYAKANANI
      Enrollment :  190540107092
      CTC per Annum :  4.32 - 4.80 Lac
      City :  Ahmedabad

23  -> RUSHIKKARAVADIYA
      Enrollment :  190540107102
      CTC per Annum :  4.32 - 4.80 Lac
      City :  Ahmedabad

24  -> JENILVASOYA
      Enrollment :  190540107222
      CTC per Annum :  4.32 - 4.80 Lac
      City :  Ahmedabad

25  -> SMIT VAGHASIYA
      Enrollment :  190540107214
      CTC per Annum :  4.50 Lac
      City :  Ahmedabad

26  -> MILANBHALODIYA
      Enrollment :  190540107008
      CTC per Annum :  4.50 Lac
      City :  Rajkot

27  -> RUSHITA SAVALIYA
      Enrollment :  190540107186
      CTC per Annum :  4.50 Lac
      City :  Rajkot

28  -> KASHYAPGINOYA
      Enrollment :  190540107068
      CTC per Annum :  4.50 Lac
      City :  Rajkot

29  -> SAVANSORATHIYA
      Enrollment :  190540107200
      CTC per Annum :  4.50 Lac
      City :  Rajkot

30  -> DIPALIBENBHUVA
      Enrollment :  190540107018
      CTC per Annum :  4.50 Lac
      City :  Rajkot

31  -> GAURAVVALA
      Enrollment :  200540107517
      CTC per Annum :  4.20 Lac
      City :  Ahmedabad

32  -> BHAVYLADANI
      Enrollment :  190540107117
      CTC per Annum :  4.20 Lac
      City :  Ahmedabad

33  -> VANSHILPATEL
      Enrollment :  190540107165
      CTC per Annum :  4.20 Lac
      City :  Rajkot

34  -> JEET PATEL
      Enrollment :  200540107504
      CTC per Annum :  4.20 Lac
      City :  Rajkot

35  -> SHUBHAMSHAH
      Enrollment :  190540107190
      CTC per Annum :  4.20 Lac
      City :  Rajkot

36  -> RADHIKARANGANI
      Enrollment :  190540107173
      CTC per Annum :  4.20 Lac
      City :  Rajkot

37  -> BURHANMAKDA
      Enrollment :  190540107128
      CTC per Annum :  4.20 Lac
      City :  Rajkot

38  -> BHAVISHAPANJWANI
      Enrollment :  190540107149
      CTC per Annum :  4.20 Lac
      City :  Rajkot

39  -> JAHNAVIDARANIA
      Enrollment :  190540107039
      CTC per Annum :  4.20 Lac
      City :  Rajkot

40  -> MAYURDHWAJSINHGOHIL
      Enrollment :  190540107070
      CTC per Annum :  4.20 Lac
      City :  Rajkot

41  -> HIMANSHULADVA
      Enrollment :  190540107118
      CTC per Annum :  4.20 Lac
      City :  Rajkot

42  -> YASHSAVALIYA
      Enrollment :  190540107187
      CTC per Annum :  4.20 Lac
      City :  Rajkot

43  -> DARSHITKUMARGADHIYA
      Enrollment :  190540107057
      CTC per Annum :  4.20 Lac
      City :  Ahmedabad

44  -> KHUSHIDADHANIYA
      Enrollment :  190540107036
      CTC per Annum :  4.20 Lac
      City :  Ahmedabad

45  -> DIVYANSHURANPARIA
      Enrollment :  190540107174
      CTC per Annum :  4.20 Lac
      City :  Ahmedabad

46  -> CHINTANKANSAGARA
      Enrollment :  190540107097
      CTC per Annum :  4.20 Lac
      City :  Ahmedabad

47  -> KENILMENDAPARA
      Enrollment :  190540107136
      CTC per Annum :  4.20 Lac
      City :  Ahmedabad

48  -> NENCYMAKADIA
      Enrollment :  190540107124
      CTC per Annum :  4.20 Lac
      City :  Ahmedabad

49  -> JAYSOLANKI
      Enrollment :  190540107197
      CTC per Annum :  4.20 Lac
      City :  Ahmedabad

50  -> NAYANMEVA
      Enrollment :  190540107137
      CTC per Annum :  4.20 Lac
      City :  Ahmedabad

51  -> TEJMODI
      Enrollment :  190540107138
      CTC per Annum :  4.20 Lac
      City :  Ahmedabad

52  -> HASTIJASANI
      Enrollment :  190540107079
      CTC per Annum :  4.20 Lac
      City :  Ahmedabad

53  -> RAJLAKKAD
      Enrollment :  190540107120
      CTC per Annum :  4.20 Lac
      City :  Ahmedabad

54  -> VIVEKPATORIYA
      Enrollment :  190540107167
      CTC per Annum :  4.00 Lac
      City :  Rajkot

55  -> KEVINMUNGRA
      Enrollment :  190540107139
      CTC per Annum :  4.00 Lac
      City :  Ahmedabad

56  -> HARSHALKHAMBHADIYA
      Enrollment :  190540107108
      CTC per Annum :  4.00 Lac
      City :  Ahmedabad

57  -> HEMALIBEN SANANDIYA
      Enrollment :  190540107180
      CTC per Annum :  4.00 Lac
      City :  Ahmedabad

58  -> PRASADMEHTA
      Enrollment :  190540107135
      CTC per Annum :  4.00 Lac
      City :  Ahmedabad

59  -> PULINDIDHANESHA
      Enrollment :  190540107048
      CTC per Annum :  4.00 Lac
      City :  Ahmedabad

60  -> JAYKUMARMANSURIYA
      Enrollment :  190540107131
      CTC per Annum :  4.00 Lac
      City :  Ahmedabad

61  -> ISHANBHATT
      Enrollment :  190540107011
      CTC per Annum :  4.00 Lac
      City :  Ahmedabad

62  -> HARDIKCHOKSI
      Enrollment :  190540107029
      CTC per Annum :  4.00 Lac
      City :  Ahmedabad

63  -> BURHANBHARMAL
      Enrollment :  190540107010
      CTC per Annum :  4.00 Lac
      City :  Ahmedabad

64  -> DARSHIT SHAH
      Enrollment :  190540107189
      CTC per Annum :  4.00 Lac
      City :  Ahmedabad

65  -> VANDITJOSHI
      Enrollment :  200540107510
      CTC per Annum :  4.00 Lac
      City :  Ahmedabad

66  -> AKASHPAMBHAR
      Enrollment :  190540107146
      CTC per Annum :  4.00 Lac
      City :  Ahmedabad

67  -> DHARMIKPARMAR
      Enrollment :  190540107153
      CTC per Annum :  4.00 Lac
      City :  Ahmedabad

68  -> SEJALGUPTA
      Enrollment :  190540107073
      CTC per Annum :  4.00 Lac
      City :  Ahmedabad

69  -> KEVANGHORECHA
      Enrollment :  190540107067
      CTC per Annum :  3.50-4.50 Lac
      City :  Ahmedabad

70  -> JANVIBAHENJANI
      Enrollment :  200540107507
      CTC per Annum :  3.50-4.50 Lac
      City :  Ahmedabad

71  -> NAKSHIKALOLIA
      Enrollment :  190544107001
      CTC per Annum :  4.00 Lac
      City :  Rajkot

72  -> SHREYAOGANJA
      Enrollment :  190540107143
      CTC per Annum :  4.00 Lac
      City :  Rajkot

73  -> JAYDEEPMITHANI
      Enrollment :  200540107512
      CTC per Annum :  4.00 Lac
      City :  Rajkot

74  -> NILONI SONI
      Enrollment :  190540107198
      CTC per Annum :  4.00 Lac
      City :  Rajkot

75  -> ANURAGPINDORIYA
      Enrollment :  190540107169
      CTC per Annum :  4.00 Lac
      City :  Rajkot

76  -> DHAVAL GOHEL
      Enrollment :  190540107069
      CTC per Annum :  4.00 Lac
      City :  Rajkot

77  -> DHRUVKUNDALIYA
      Enrollment :  190540107114
      CTC per Annum :  4.00 Lac
      City :  Rajkot

78  -> RUTULSORATHIYA
      Enrollment :  190540107199
      CTC per Annum :  4.00 Lac
      City :  Rajkot

79  -> DHRUVILDOBARIYA
      Enrollment :  190540107051
      CTC per Annum :  4.00 Lac
      City :  Rajkot

80  -> SHIVAMNANDA
      Enrollment :  200540107518
      CTC per Annum :  4.00 Lac
      City :  Rajkot

81  -> RINKLEADVANI
      Enrollment :  190540107002
      CTC per Annum :  4.00 Lac
      City :  Rajkot

82  -> PRIYAMODI
      Enrollment :  200540107522
      CTC per Annum :  4.00 Lac
      City :  Rajkot

83  -> PARTHDAMANI
      Enrollment :  190540107037
      CTC per Annum :  4.00 Lac
      City :  Rajkot

84  -> DEEPKANANI
      Enrollment :  190540107091
      CTC per Annum :  3.00 - 5.00 Lac
      City :  Ahmedabad

85  -> SMITKUMARPADSUMBIYA
      Enrollment :  190540107144
      CTC per Annum :  3.00-5.00 Lac
      City :  Ahmedabad

86  -> DIVYTHAKRAR
      Enrollment :  190540107206
      CTC per Annum :  3.00-5.00 Lac
      City :  Ahmedabad

87  -> VATSALBABARIYA
      Enrollment :  200540107503
      CTC per Annum :  3.00-5.00 Lac
      City :  Ahmedabad

88  -> SMITMESHVANIYA
      Enrollment :  200540107506
      CTC per Annum :  3.00-5.00 Lac
      City :  Ahmedabad

89  -> URMILPARSANIYA
      Enrollment :  200540107513
      CTC per Annum :  3.00-5.00 Lac
      City :  Ahmedabad

90  -> KRUSHNAJOSHI
      Enrollment :  190540107083
      CTC per Annum :  3.00-5.00 Lac
      City :  Ahmedabad

91  -> VIRAJBUSA
      Enrollment :  190540107021
      CTC per Annum :  4.00 Lac
      City :  Rajkot

92  -> MONIKABENDETROJA
      Enrollment :  190540107046
      CTC per Annum :  4.00 Lac
      City :  Rajkot

93  -> ABHAYKAMANI
      Enrollment :  190540107089
      CTC per Annum :  3.00-4.80 Lac
      City :  Ahmedabad

94  -> VARUNKESARIA
      Enrollment :  190540107107
      CTC per Annum :  3.84 Lac
      City :  Ahmedabad

95  -> VIVEKPARMAR
      Enrollment :  200540107521
      CTC per Annum :  3.60-4.00 Lac
      City :  Ahmedabad

96  -> PARTHPANDYA
      Enrollment :  190540107147
      CTC per Annum :  3.50 - 4.00 Lac
      City :  Rajkot

97  -> DEVANGMEHTA
      Enrollment :  190540107134
      CTC per Annum :  3.50 - 4.00 Lac
      City :  Rajkot

98  -> KARANDAVDA
      Enrollment :  190540107041
      CTC per Annum :  3.50 - 4.00 Lac
      City :  Rajkot

99  -> DIGVIJAYNAKUM
      Enrollment :  190540107141
      CTC per Annum :  3.50 - 4.00 Lac
      City :  Rajkot

100  -> JAYDEVCHOTAI
      Enrollment :  190540107031
      CTC per Annum :  3.50 - 4.00 Lac
      City :  Rajkot

101  -> HARSHILDHOLAKIYA
      Enrollment :  190540107049
      CTC per Annum :  3.50 - 4.00 Lac
      City :  Rajkot

102  -> DARSHAYBHAYANI
      Enrollment :  190540107012
      CTC per Annum :  3.50 - 4.00 Lac
      City :  Rajkot

103  -> DARSHANKANGAD
      Enrollment :  190540107096
      CTC per Annum :  3.72 Lac
      City :  Rajkot

104  -> SAHILVASANI
      Enrollment :  190540107220
      CTC per Annum :  3.60 Lac
      City :  Ahmedabad

105  -> SAKSHIBENPATEL
      Enrollment :  200540107505
      CTC per Annum :  3.60 Lac
      City :  Ahmedabad

106  -> DEVANSHIMAKHECHA
      Enrollment :  190540107129
      CTC per Annum :  3.60 Lac
      City :  Ahmedabad

107  -> PRATHAMVYAS
      Enrollment :  190540107227
      CTC per Annum :  3.00-4.20 Lac
      City :  Ahmedabad

108  -> VISHVADEEPVAMJA
      Enrollment :  180540107182
      CTC per Annum :  3.00-4.20 Lac
      City :  Ahmedabad

109  -> MITESHBHIMANI
      Enrollment :  190540107015
      CTC per Annum :  3.60 Lac
      City :  Gandhinagar

110  -> VRUTIKKUMARMUNGRA
      Enrollment :  190540107140
      CTC per Annum :  3.60 Lac
      City :  Gandhinagar

111  -> BIRJUBHAISAVANI
      Enrollment :  190540107188
      CTC per Annum :  3.60 Lac
      City :  Gandhinagar

112  -> YASHKUMARVARMORA
      Enrollment :  190540107219
      CTC per Annum :  3.60 Lac
      City :  Gandhinagar

113  -> SHYAMKADECHA
      Enrollment :  190540107087
      CTC per Annum :  3.60 Lac
      City :  Gandhinagar

114  -> PRARTHANAKARIYA
      Enrollment :  190540107103
      CTC per Annum :  3.60 Lac
      City :  Rajkot

115  -> OMGAJERA
      Enrollment :  190540107060
      CTC per Annum :  3.00-4.00 Lac
      City :  Ahmedabad

116  -> DHAVALDOBARIYA
      Enrollment :  190540107050
      CTC per Annum :  3.50 Lac
      City :  Ahmedabad

117  -> HARSHALGAMI
      Enrollment :  190540107063
      CTC per Annum :  3.50 Lac
      City :  Ahmedabad

118  -> KALPGORECHA
      Enrollment :  190540107072
      CTC per Annum :  3.50 Lac
      City :  Ahmedabad

119  -> TIRTHANAKANSAGARA
      Enrollment :  190540107098
      CTC per Annum :  3.50 Lac
      City :  Ahmedabad

120  -> KEVINKANZARIYA
      Enrollment :  190540107100
      CTC per Annum :  3.50 Lac
      City :  Ahmedabad

121  -> SAHILKUMARKIKANI
      Enrollment :  190540107111
      CTC per Annum :  3.50 Lac
      City :  Ahmedabad

122  -> DHRUV PARMAR
      Enrollment :  190540107155
      CTC per Annum :  3.50 Lac
      City :  Ahmedabad

123  -> VIVEKPESHAVARIYA
      Enrollment :  190540107168
      CTC per Annum :  3.50 Lac
      City :  Ahmedabad

124  -> JAY PIPALIYA
      Enrollment :  190540107170
      CTC per Annum :  3.50 Lac
      City :  Ahmedabad

125  -> BHARGAVKUMARVACHHANI
      Enrollment :  19054010721
      CTC per Annum :  3.50 Lac
      City :  Ahmedabad

126  -> KEVALSARDHARA
      Enrollment :  190540107183
      CTC per Annum :  3.50 Lac
      City :  Ahmedabad

127  -> ISHAVAGHAMSHI
      Enrollment :  190540107213
      CTC per Annum :  3.50 Lac
      City :  Ahmedabad

128  -> CHINTANKUMARSAKHIYA
      Enrollment :  190540107179
      CTC per Annum :  3.50 Lac
      City :  Rajkot

129  -> HAPPYKUMARGADARA
      Enrollment :  190540107056
      CTC per Annum :  4.64-4.20 Lac
      City :  Ahmedabad

130  -> MUKESHJAMOD
      Enrollment :  190540107077
      CTC per Annum :  3.25-3.50 Lac
      City :  Ahmedabad

131  -> SANDIPAPANI
      Enrollment :  190540107004
      CTC per Annum :  3.25-3.50 Lac
      City :  Ahmedabad

132  -> DHARTISOLANKI
      Enrollment :  200540107502
      CTC per Annum :  3.00-3.60 Lac
      City :  Ahmedabad

133  -> DAKSHITTHUMMAR
      Enrollment :  190540107207
      CTC per Annum :  3.00-3.50 Lac
      City :  Ahmedabad

134  -> RUSHIKKUMARSUTARIYA
      Enrollment :  190540107202
      CTC per Annum :  3.00-3.50 Lac
      City :  Ahmedabad

135  -> RAHULSAVANI
      Enrollment :  200540107508
      CTC per Annum :  3.00 Lac
      City :  Ahmedabad

136  -> RITIKACHAUHAN
      Enrollment :  190540107023
      CTC per Annum :  3.00 Lac
      City :  Ahmedabad

137  -> SHIVANIDESHANI
      Enrollment :  190540107044
      CTC per Annum :  3.00 Lac
      City :  Gandhinagar

138  -> VISHWASUBA
      Enrollment :  190540107201
      CTC per Annum :  3.00 Lac
      City :  Gandhinagar

139  -> VIRAJVEKARIYA
      Enrollment :  190540107223
      CTC per Annum :  3.00 Lac
      City :  Gandhinagar

140  -> KEYURJETHVA
      Enrollment :  190540107080
      CTC per Annum :  3.00 Lac
      City :  Gandhinagar

141  -> RIDDHIPARMAR
      Enrollment :  190540107159
      CTC per Annum :  3.00 Lac
      City :  Rajkot

142  -> DHRUVIKANERIYA
      Enrollment :  190540107094
      CTC per Annum :  3.00 Lac
      City :  Rajkot

143  -> DHAIVATVAGHELA
      Enrollment :  190540107215
      CTC per Annum :  3.00 Lac
      City :  Rajkot

144  -> YASHJANANI
      Enrollment :  190540107078
      CTC per Annum :  3.00 Lac
      City :  Rajkot

145  -> MILANRATHOD
      Enrollment :  190540107176
      CTC per Annum :  3.00 Lac
      City :  Ahmedabad

146  -> DAXITBHUPTANI
      Enrollment :  190540107017
      CTC per Annum :  3.00 Lac
      City :  Rajkot

147  -> VISHWASADARIYA
      Enrollment :  200540107501
      CTC per Annum :  3.00 Lac
      City :  Rajkot

148  -> SAGARTANK
      Enrollment :  190540107205
      CTC per Annum :  3.00 Lac
      City :  Rajkot

149  -> JEELDETROJA
      Enrollment :  190540107045
      CTC per Annum :  Confidential
      City :  Ahmedabad

150  -> VIVEKDUBARIYA
      Enrollment :  190540107053
      CTC per Annum :  Confidential
      City :  Ahmedabad

151  -> PRINCEFALDU
      Enrollment :  190540107054
      CTC per Annum :  Confidential
      City :  Ahmedabad

152  -> RUSHIKDARANIYA
      Enrollment :  190540107040
      CTC per Annum :  Confidential
      City :  Ahmedabad

153  -> ISHITVASOYA
      Enrollment :  190540107221
      CTC per Annum :  2.64 Lac
      City :  Rajkot

154  -> KRUNALPATEL
      Enrollment :  190540107163
      CTC per Annum :  2.64 Lac
      City :  Rajkot

155  -> KRIPALHUMBAL
      Enrollment :  190540107075
      CTC per Annum :  2.40 Lac
      City :  Rajkot

IndexError: list index out of range

# Write a python program to perform database operations on database using mysql and sqlite3.
1)	 Display Student table from database.<br>
2)	Insert new recode into student table by user.

In [ ]:
import sqlite3
connection = sqlite3.connect("bcd.db")
crsr = connection.cursor()
print("Connected to the database")
#connection.close()

#create student table
sql_command = """CREATE TABLE Student_table (
roll_no INTEGER PRIMARY KEY,
fname VARCHAR(50),
lname VARCHAR(50),
cpi FLOAT,
city VARCHAR(20));"""
crsr.execute(sql_command)
#connection.close()

sql_command = """INSERT INTO Student_table VALUES 
(1, "abc", "xyz", 9.2, "Rajkot");"""
crsr.execute(sql_command)
sql_command = """INSERT INTO Student_table VALUES 
(2, "def", "pqr", 8.9, "Rajkot");"""
crsr.execute(sql_command)
sql_command = """INSERT INTO Student_table VALUES 
(3, "ghi", "stu", 7, "Jamnagar");"""
crsr.execute(sql_command)
sql_command = """INSERT INTO Student_table VALUES 
(4, "jkl", "sqr", 9.21, "Jamnagar");"""
crsr.execute(sql_command)
sql_command = """INSERT INTO Student_table VALUES 
(5, "mno", "mno", 8.66, "Morbi");"""
crsr.execute(sql_command)
connection.commit()
#connection.close()

crsr.execute("SELECT * FROM Student_table;")
ans = crsr.fetchall()
for i in ans:
  print(i)



rno = input("Enter roll number : ")
f_nm = input("Enter first name : ")
l_nm = input("Enter last name : ")
cpi = input("Enter CPI : ")
ct = input("Enter city : ")
 
crsr.execute("""
INSERT INTO Student_table(roll_no, fname, lname, cpi, city)
VALUES (?,?,?,?,?)
""", (rno, f_nm, l_nm, cpi, ct))

connection.commit()
#connection.close()


crsr.execute("SELECT * FROM Student_table;")
ans = crsr.fetchall()
for i in ans:
  print(i)

Connected to the database
(1, 'abc', 'xyz', 9.2, 'Rajkot')
(2, 'def', 'pqr', 8.9, 'Rajkot')
(3, 'ghi', 'stu', 7.0, 'Jamnagar')
(4, 'jkl', 'sqr', 9.21, 'Jamnagar')
(5, 'mno', 'mno', 8.66, 'Morbi')